/STSS/FY3E_STSS/A/bin/python3 GNOS_day.py 
/STSS/FY3E_STSS/A/bin/python3 HIRAS_day.py 
/STSS/FY3E_STSS/A/bin/python3 MWHS_day.py 
/STSS/FY3E_STSS/A/bin/python3 MWTS_day.py 
/STSS/FY3E_STSS/A/bin/python3 SEM_day.py 
/STSS/FY3E_STSS/A/bin/python3 TRIPM_day.py 
/STSS/FY3E_STSS/A/bin/python3 WRADC_day.py 
/STSS/FY3E_STSS/A/bin/python3 WRADK_day.py 
/STSS/FY3E_STSS/A/bin/python3 XEUVI_day.py 